version: '3.7'

services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning
    networks:
      - watchtower
      - default

volumes:
  grafana: {}

networks:
  watchtower:
    external:
      name: watchtower
